development: &default
  adapter: postgresql
  encoding: unicode
  # database: postgres
  database: storedom_dev
  pool: 5
  username: postgres
  password:
  host: postgres

test:
  <<: *default
  database: storedom_test

production:
  <<: *default
  database: storedom
